INSERT INTO anime (anime_id,
                   anime_jikan_id,
                   anime_aired_end,
                   anime_aired_start,
                   anime_broadcast,
                   anime_description,
                   anime_demographic,
                   anime_duration,
                   anime_episodes,
                   anime_genres,
                   anime_instagram_url,
                   anime_official_website_url,
                   anime_producer,
                   anime_rating,
                   anime_status,
                   anime_title,
                   anime_title_alt,
                   anime_twitter_url,
                   anime_type)
VALUES ('d2e4feeb-45c9-4c5b-8d3c-b77d57869fc3',
        12345,
        '2022-12-30',
        '2021-01-10',
        'Sundays at 10:00 AM',
        'A thrilling adventure of a young hero who discovers a hidden power within himself, embarking on an epic journey to save his world from a mysterious threat.',
        'Shounen',
        24.5,
        24,
        'Action, Adventure, Fantasy',
        'https://www.instagram.com/hero_anime',
        'https://www.heroanime.com',
        'Studio X, Hero Production',
        8.7,
        'Finished',
        'The Heros Journey',
        'Journey of the Hero',
        'https://twitter.com/hero_anime',
        'TV Series'),
       ('f98d24b4-2637-4a22-9485-84b54f2f76ea',
        67890,
        '2023-08-15',
        '2022-05-20',
        'Fridays at 7:00 PM',
        'A slice-of-life story about a group of friends discovering the meaning of life while pursuing their dreams together.',
        'Seinen',
        22.0,
        12,
        'Drama, Slice-of-Life',
        'https://www.instagram.com/life_dreams_anime',
        'https://www.lifedreams.com',
        'Life Studio, DreamWorks Productions',
        9.2,
        'Ongoing',
        'Life & Dreams',
        'Dreams of Life',
        'https://twitter.com/life_dreams_anime',
        'TV Series'),
       ('f35c2b93-5a4b-42f0-a064-fd729479e6f7',
        24680,
        '2024-05-10',
        '2023-06-25',
        'Wednesdays at 9:00 PM',
        'A supernatural thriller where a group of detectives must solve bizarre crimes related to mysterious paranormal events occurring in their city.',
        'Mystery',
        30.0,
        24,
        'Mystery, Supernatural, Thriller',
        'https://www.instagram.com/paranormal_cases_anime',
        'https://www.paranormalcases.com',
        'Ghost Works, Crime Corp',
        8.4,
        'Upcoming',
        'Paranormal Cases',
        'Cases Beyond',
        'https://twitter.com/paranormal_cases_anime',
        'TV Series'),
       ('a994d139-b8db-492d-a84b-b2cbe2c37849',
        13579,
        '2024-03-01',
        '2023-08-15',
        'Mondays at 8:00 PM',
        'A lighthearted comedy about a student who ends up in a magical school, where he must navigate his new life while trying to keep his secret identity hidden.',
        'Shounen',
        20.0,
        16,
        'Comedy, Magic, School',
        'https://www.instagram.com/magic_student_anime',
        'https://www.magicstudent.com',
        'Magic Studios, New Age Productions',
        7.5,
        'Finished',
        'The Magic Student',
        'Secret Magic',
        'https://twitter.com/magic_student_anime',
        'TV Series');
